# Generated by Django 2.0.6 on 2018-06-27 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'default_permissions': ('add', 'change', 'delete')},
        ),
    ]
