# Generated by Django 2.0.6 on 2018-06-28 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180628_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='created_by',
            new_name='author',
        ),
    ]
