# Generated by Django 2.0.6 on 2018-07-01 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180701_0505'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='content',
        ),
    ]
